#!/usr/bin/env bash
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
lock_file="$repo_root/deploy/sysbox-source.lock"
sysbox_repo="https://github.com/nestybox/sysbox.git"

usage() {
	echo "usage: $0 check | update <version>" >&2
	exit 2
}

fail() {
	echo "sysbox source lock: $*" >&2
	exit 1
}

lock_value() {
	local key="$1"
	local values=()

	mapfile -t values < <(awk -v key="$key" '$1 == key && $2 == ":=" { print $3 }' "$lock_file")
	[[ "${#values[@]}" -eq 1 ]] || fail "expected exactly one $key entry in $lock_file"
	printf '%s\n' "${values[0]}"
}

validate_lock_format() {
	local line
	local key
	local value
	local expected_keys=(
		SYSBOX_VERSION
		SYSBOX_RELEASE_COMMIT
		SYSBOX_IPC_COMMIT
		SYSBOX_LIBS_COMMIT
		SYSBOX_RUNC_COMMIT
		SYSBOX_SHA_linux_amd64
		SYSBOX_SHA_linux_arm64
	)

	[[ -f "$lock_file" ]] || fail "missing $lock_file"
	while IFS= read -r line || [[ -n "$line" ]]; do
		case "$line" in
		"" | \#*) ;;
		*" := "*)
			key="${line%% := *}"
			case " ${expected_keys[*]} " in
			*" $key "*) ;;
			*) fail "unexpected key $key in $lock_file" ;;
			esac
			;;
		*) fail "malformed line in $lock_file: $line" ;;
		esac
	done <"$lock_file"

	value="$(lock_value SYSBOX_VERSION)"
	[[ "$value" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || fail "invalid SYSBOX_VERSION: $value"
	for key in SYSBOX_RELEASE_COMMIT SYSBOX_IPC_COMMIT SYSBOX_LIBS_COMMIT SYSBOX_RUNC_COMMIT; do
		value="$(lock_value "$key")"
		[[ "$value" =~ ^[0-9a-f]{40}$ ]] || fail "invalid $key: $value"
	done
	for key in SYSBOX_SHA_linux_amd64 SYSBOX_SHA_linux_arm64; do
		value="$(lock_value "$key")"
		[[ "$value" =~ ^[0-9a-f]{64}$ ]] || fail "invalid $key: $value"
	done
}

resolve_release() {
	local version="$1"
	local metadata_dir="$2"
	local path
	local entry
	local mode
	local type
	local value
	local name

	git init --quiet "$metadata_dir"
	git -C "$metadata_dir" remote add origin "$sysbox_repo"
	git -C "$metadata_dir" -c http.version=HTTP/1.1 fetch \
		--quiet \
		--depth 1 \
		--filter=blob:none \
		origin \
		"refs/tags/v${version}:refs/tags/v${version}"

	RELEASE_COMMIT="$(git -C "$metadata_dir" rev-parse "v${version}^{commit}")"
	for path in sysbox-ipc sysbox-libs sysbox-runc; do
		entry="$(git -C "$metadata_dir" ls-tree "$RELEASE_COMMIT" "$path")"
		read -r mode type value name <<<"$entry"
		[[ "$mode" == "160000" && "$type" == "commit" && "$name" == "$path" ]] || \
			fail "release v$version has no $path gitlink"
		case "$path" in
		sysbox-ipc) IPC_COMMIT="$value" ;;
		sysbox-libs) LIBS_COMMIT="$value" ;;
		sysbox-runc) RUNC_COMMIT="$value" ;;
		esac
	done
}

package_sha() {
	local version="$1"
	local arch="$2"
	local destination="$3"
	local package="sysbox-ce_${version}-0.linux_${arch}.deb"

	curl \
		--fail \
		--location \
		--retry 3 \
		--show-error \
		--silent \
		--output "$destination" \
		"https://downloads.nestybox.com/sysbox/releases/v${version}/${package}"
	sha256sum "$destination" | awk '{ print $1 }'
}

check_lock() {
	local temporary_dir="$1"
	local version

	validate_lock_format
	version="$(lock_value SYSBOX_VERSION)"
	resolve_release "$version" "$temporary_dir/sysbox"

	[[ "$(lock_value SYSBOX_RELEASE_COMMIT)" == "$RELEASE_COMMIT" ]] || fail "release commit does not match v$version"
	[[ "$(lock_value SYSBOX_IPC_COMMIT)" == "$IPC_COMMIT" ]] || fail "sysbox-ipc commit does not match v$version"
	[[ "$(lock_value SYSBOX_LIBS_COMMIT)" == "$LIBS_COMMIT" ]] || fail "sysbox-libs commit does not match v$version"
	[[ "$(lock_value SYSBOX_RUNC_COMMIT)" == "$RUNC_COMMIT" ]] || fail "sysbox-runc commit does not match v$version"

	printf 'Sysbox v%s source lock is valid.\n' "$version"
}

update_lock() {
	local temporary_dir="$1"
	local version="${2#v}"
	local amd64_sha
	local arm64_sha
	local generated_lock="$temporary_dir/sysbox-source.lock"

	[[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || fail "invalid version: $version"
	resolve_release "$version" "$temporary_dir/sysbox"
	amd64_sha="$(package_sha "$version" amd64 "$temporary_dir/sysbox-amd64.deb")"
	arm64_sha="$(package_sha "$version" arm64 "$temporary_dir/sysbox-arm64.deb")"

	{
		printf '# Generated by scripts/sysbox_source_lock.sh. Do not edit manually.\n'
		printf '# Source: https://github.com/nestybox/sysbox/tree/v%s\n' "$version"
		printf 'SYSBOX_VERSION := %s\n' "$version"
		printf 'SYSBOX_RELEASE_COMMIT := %s\n' "$RELEASE_COMMIT"
		printf 'SYSBOX_IPC_COMMIT := %s\n' "$IPC_COMMIT"
		printf 'SYSBOX_LIBS_COMMIT := %s\n' "$LIBS_COMMIT"
		printf 'SYSBOX_RUNC_COMMIT := %s\n' "$RUNC_COMMIT"
		printf 'SYSBOX_SHA_linux_amd64 := %s\n' "$amd64_sha"
		printf 'SYSBOX_SHA_linux_arm64 := %s\n' "$arm64_sha"
	} >"$generated_lock"

	mv "$generated_lock" "$lock_file"
	printf 'Updated %s for Sysbox v%s.\n' "$lock_file" "$version"
}

[[ "$#" -ge 1 ]] || usage
temporary_dir="$(mktemp -d /tmp/envbox-sysbox-lock.XXXXXX)"
trap 'rm -rf "$temporary_dir"' EXIT

case "$1" in
check)
	[[ "$#" -eq 1 ]] || usage
	check_lock "$temporary_dir"
	;;
update)
	[[ "$#" -eq 2 ]] || usage
	update_lock "$temporary_dir" "$2"
	;;
*) usage ;;
esac
